App\Entity\User:
    properties:
        roles:
            - App\Validator\Constraints\Role: { groups: [RolesUpdate] }
        username:
            - NotBlank: { groups: [Registration, UserCreate, Profile] }
            - Length: { min: 2, max: 60, groups: [Registration, UserCreate, Profile] }
        email:
            - NotBlank: { groups: [Registration, UserCreate, Profile] }
            - Email: { groups: [Registration, UserCreate, Profile] }
        plainPassword:
            - NotBlank: { groups: [Registration, PasswordUpdate, UserCreate] }
            - Length: { min: 8, max: 60, groups: [Registration, PasswordUpdate, UserCreate] }
        plainApiToken:
            - NotBlank: { groups: [ApiTokenUpdate] }
            - Length: { min: 8, max: 60, groups: [ApiTokenUpdate] }
